# Diabetes Classification

Classification practice notebook for the diabetes dataset.
> - 분류: 어떤 카테고리에 속하는지 예측 
> - Outcome 을 제거한 데이터로 당뇨인지 아닌지를 예측하는 실습
---
> 정확도 기준으로 Logistic Regression이 가장 높은 성능을 보였고, 다른 두 모델은 상대적으로 낮은 성능을 보였다.

### 도구 설정 및 데이터 불러오기
1. 데이터 분석을 위해 pandas 를 불러오며 pd 로 줄임(사용편의)
2. 수치 계산을 위해 numpy 를 불러오며 np 로 줄임(사용편의)
3. 로지스틱 리그레션 모델을 불러옴 (diabetes 데이터의 outcome이 0과 1로 이루어져 있기 때문에 이진분류에 적합한 모델인 로지스틱 회귀 모델을 사용)
4. 성능 비교를 위해 다른 모델 디시젼트리와 랜덤포레스트도 불러옴
5. 분류 모델의 성능을 평가하기위해 accuracy_score 를 불러옴 (전체적으로 몇개 맞췄는지 평가하는 지표)
6. 분류 모델의 성능을 평가하기위해 confusion_matrix 를 불러옴 (어떤 종류의 실수가 있었는지 평가하는 지표)
7. 데이터를 훈련용과 테스트용으로 나누는 함수 train_test_split 을 불러옴 (train 데이터: 모델 공부시키는 용도 / test 데이터: 공부 안 시킨 새 문제로 성능 확인하는 용도)

In [1]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split


In [ ]:
path = '/Users/ganghyejun/Desktop/100_College/2-1/인공지능개론/AICLASS_2-1/task/src/data/diabetes.csv' #데이터 파일 경로
df = pd.read_csv(path, index_col=0)
df

# pandas 라이브러리를 이용해 csv 파일을 읽어와 df에 저장
# index_col=0 : 쓸모없는 첫 번째 열을 인덱스로 빼버리니까, 실제 데이터 컬럼들이 한 칸씩 정상 위치로 정리됨

,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
Pregnancies,,,,,,,,
6,148,72,35,0,33.6,0.627,50,1
1,85,66,29,0,26.6,0.351,31,0
8,183,64,0,0,23.3,0.672,32,1
1,89,66,23,94,28.1,0.167,21,0
0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...
10,101,76,48,180,32.9,0.171,63,0
2,122,70,27,0,36.8,0.340,27,0
5,121,72,23,112,26.2,0.245,30,0


### 데이터 정제
- Outcome 열을 y로 저장 (Outcome 열이 우리가 예측하려는 타겟값이기 때문)
- Outcome 열의 각 값이 몇개씩 있는지 세어서 보여줌 (0과 1이 각각 몇개씩 있는지 확인)

- Outcome 열을 제거한 값을 X로 저장 (,,)

- train_test_split 함수를 이용해 데이터를 훈련용과 테스트용으로 나눔
- test_size=0.25 : 전체 데이터의 25%를 테스트용으로 사용 (표본이 많으면 정확도가 올라감)
> - random_state=0 : 데이터를 나누는 방식 고정 (0으로 설정) 
>   - 데이터를 무작위로 나누되, 실행할 때마다 같은 방식으로 나뉘도록 고정하는 값

In [3]:
y=df['Outcome']
y.value_counts()

X=df.drop('Outcome',axis=1)
X.head()

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)

### 실행
1. 훈련
- LogisticRegression 클래스의 객체를 생성하여 clf_lr에 저장 (훈련하고 테스트를 진행할 모델을 만듬)
- clf_lr 객체의 fit 메소드를 이용해 훈련용 데이터 X_train과 y_train을 이용해 모델을 학습시킴

2. 테스트
- clf_lr 객체의 predict 메소드를 이용해 테스트용 데이터 X_test에 대한 예측값을 pred_lr에 저장

3. 성능 평가
- accuracy_score 와 confusion_matrix 를 사용해 평가 후 지표를 출력

In [4]:
clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


clf_rf = RandomForestClassifier(random_state=0)
clf_rf.fit(X_train, y_train)

pred_rf = clf_rf.predict(X_test)

print ("\n--- Random Forest Classifier ---")
print (accuracy_score(y_test, pred_rf))
print (confusion_matrix(y_test, pred_rf))


--- Logistic Regression Classifier ---
0.7916666666666666
[[116  14]
 [ 26  36]]

--- Decision Tree Classifier ---
0.7447916666666666
[[103  27]
 [ 22  40]]

--- Random Forest Classifier ---
0.7760416666666666
[[114  16]
 [ 27  35]]


/Users/ganghyejun/Desktop/100_College/2-1/인공지능개론/AICLASS_2-1/.venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
