# Wine Classification

Classification practice notebook for the breath cancer dataset.
> - 분류: 어떤 카테고리에 속하는지 예측 
> - wine 을 제거한 데이터로 어떤 와인인지를 예측하는 실습

### 도구 설정 및 데이터 불러오기
1. 로지스틱, 디시젼트리, 랜덤포레스트 분류에 필요한 세가지 모델을 불러옴
2. 분류 모델의 성능을 평가하기위해 accuracy_score 를 불러옴 (전체적으로 몇개 맞췄는지 평가하는 지표)
3. 분류 모델의 성능을 평가하기위해 confusion_matrix 를 불러옴 (어떤 종류의 실수가 있었는지 평가하는 지표)
4. 데이터를 훈련용과 테스트용으로 나누는 함수 train_test_split 을 불러옴 (train 데이터: 모델 공부시키는 용도 / test 데이터: 공부 안 시킨 새 문제로 성능 확인하는 용도)

In [21]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split


In [22]:
path = '/Users/ganghyejun/Desktop/100_College/2-1/인공지능개론/AICLASS_2-1/task/src/data/wine.csv' #데이터 파일 경로
df = pd.read_csv(path, index_col=0) #pandas 라이브러리를 이용해 csv 파일을 읽어와 df에 저장
df

,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
Wine,,,,,,,,,,,,,
1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835


### 데이터 정제
- Wine 열을 y로 저장 (Wine 열이 우리가 예측하려는 타겟값이기 때문)
- Wine 열의 각 값이 몇개씩 있는지 세어서 보여줌 (0과 1이 각각 몇개씩 있는지 확인)

- Wine 열을 제거한 값을 X로 저장 (,,)

- train_test_split 함수를 이용해 데이터를 훈련용과 테스트용으로 나눔
- test_size=0.25 : 전체 데이터의 25%를 테스트용으로 사용
- random_state=0 : 데이터를 무작위로 나누되, 실행할 때마다 같은 방식으로 나뉘도록 고정하는 값

In [23]:
y=df['Wine']
y.value_counts()

X=df.drop('Wine',axis=1)
X.head()

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)

KeyError: 'Wine'

### 실행
1. 훈련
- LogisticRegression 클래스의 객체를 생성하여 clf_lr에 저장 (훈련하고 테스트를 진행할 모델을 만듬)
- clf_lr 객체의 fit 메소드를 이용해 훈련용 데이터 X_train과 y_train을 이용해 모델을 학습시킴

2. 테스트
- clf_lr 객체의 predict 메소드를 이용해 테스트용 데이터 X_test에 대한 예측값을 pred_lr에 저장

3. 성능 평가
- accuracy_score 와 confusion_matrix 를 사용해 평가 후 지표를 출력

In [13]:
clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- DecisionTreeClassifier Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


clf_rf = RandomForestClassifier(random_state=0)
clf_rf.fit(X_train, y_train)

pred_rf = clf_rf.predict(X_test)

print ("\n--- RandomForest Classifier ---")
print (accuracy_score(y_test, pred_rf))
print (confusion_matrix(y_test, pred_rf))


--- Logistic Regression Classifier ---
0.9333333333333333
[[14  2  0]
 [ 0 20  1]
 [ 0  0  8]]

--- DecisionTreeClassifier Classifier ---
0.9333333333333333
[[14  2  0]
 [ 0 20  1]
 [ 0  0  8]]

--- RandomForest Classifier ---
0.9777777777777777
[[16  0  0]
 [ 0 20  1]
 [ 0  0  8]]


/Users/ganghyejun/Desktop/100_College/2-1/인공지능개론/AICLASS_2-1/.venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
