# Wine Classification

wine 데이터셋을 이용해 와인의 클래스를 분류하는 딥러닝 분류를 수행하였다.
 - 이번 테스트에서는 정확도 약 0.98로 매우 높은 성능을 보였고, 대부분의 데이터를 정확하게 분류하였다.

In [5]:
import pandas as pd
import numpy as np
import tensorflow as tf

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

from tensorflow.keras import layers, models

In [6]:
path = '/Users/ganghyejun/Desktop/100_College/2-1/인공지능개론/AICLASS_2-1/task/src/data/wine.csv'
df = pd.read_csv(path)

In [7]:
y = df['Wine']
X = df.drop('Wine', axis=1)

# 1. X를 numpy로 변환 + 스케일링
scaler = StandardScaler()
X = scaler.fit_transform(X)

# 2. train/test 분리
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=0
)

# 3. y를 원-핫 인코딩
classes = sorted(y.unique())
y_train = pd.get_dummies(y_train).reindex(columns=classes, fill_value=0).values
y_test = pd.get_dummies(y_test).reindex(columns=classes, fill_value=0).values

# 4. 딥러닝 분류 모델
model = models.Sequential([
    layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    layers.Dropout(0.3),
    layers.Dense(32, activation='relu'),
    layers.Dense(y_train.shape[1], activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    X_train, y_train,
    validation_split=0.2,
    epochs=50,
    batch_size=16,
    verbose=1
)

Epoch 1/50


/Users/ganghyejun/Desktop/100_College/2-1/인공지능개론/AICLASS_2-1/.venv/lib/python3.12/site-packages/keras/src/layers/core/dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.5094 - loss: 1.0183 - val_accuracy: 0.5185 - val_loss: 0.9688
Epoch 2/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6981 - loss: 0.8446 - val_accuracy: 0.6296 - val_loss: 0.8326
Epoch 3/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7075 - loss: 0.6937 - val_accuracy: 0.7407 - val_loss: 0.7223
Epoch 4/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8113 - loss: 0.5922 - val_accuracy: 0.7778 - val_loss: 0.6304
Epoch 5/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8868 - loss: 0.4886 - val_accuracy: 0.8148 - val_loss: 0.5503
Epoch 6/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8868 - loss: 0.4126 - val_accuracy: 0.8148 - val_loss: 0.4827
Epoch 7/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9245 - loss: 0.3698 - val_accuracy: 0.9259 - val_loss: 0.4271
Epoch 8/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9245 - loss: 0.3263 - val_accuracy: 0.9259 - val_loss: 0.3765
Epoch 9/50
7/7 ━━━

In [8]:
# 5. 예측 및 평가
y_pred = model.predict(X_test)

y_test_class = np.argmax(y_test, axis=1)
y_pred_class = np.argmax(y_pred, axis=1)

print(classification_report(y_test_class, y_pred_class))
print(confusion_matrix(y_test_class, y_pred_class))

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
              precision    recall  f1-score   support

           0       1.00      0.94      0.97        16
           1       0.95      1.00      0.98        21
           2       1.00      1.00      1.00         8

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

[[15  1  0]
 [ 0 21  0]
 [ 0  0  8]]
